#!/bin/bash
# Azure CLI Configuration Script for VibeCode Studio
# This script helps set up Azure resources and configuration using Azure CLI

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
RESOURCE_GROUP_NAME="vibecode-studio-rg"
LOCATION="eastus"
AI_SERVICE_NAME="vibecode-ai-service"
DEPLOYMENT_NAME="gpt-4"

echo -e "${BLUE}🚀 VibeCode Studio - Azure CLI Setup${NC}"
echo "This script will help you configure Azure resources for VibeCode Studio"
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}❌ Azure CLI is not installed. Please install it first.${NC}"
    exit 1
fi

# Function to check if user is logged in
check_azure_login() {
    if ! az account show &> /dev/null; then
        echo -e "${YELLOW}⚠️  You are not logged in to Azure.${NC}"
        echo "Please run: az login"
        echo "Then re-run this script."
        exit 1
    fi
}

# Function to get current subscription info
get_subscription_info() {
    SUBSCRIPTION_ID=$(az account show --query id -o tsv)
    TENANT_ID=$(az account show --query tenantId -o tsv)
    SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
    
    echo -e "${GREEN}✅ Connected to Azure${NC}"
    echo "   Subscription: $SUBSCRIPTION_NAME"
    echo "   Subscription ID: $SUBSCRIPTION_ID"
    echo "   Tenant ID: $TENANT_ID"
    echo ""
}

# Function to create resource group
create_resource_group() {
    echo -e "${BLUE}📦 Creating Resource Group...${NC}"
    
    if az group show --name $RESOURCE_GROUP_NAME --output none 2>/dev/null; then
        echo -e "${YELLOW}⚠️  Resource group '$RESOURCE_GROUP_NAME' already exists.${NC}"
    else
        az group create --name $RESOURCE_GROUP_NAME --location $LOCATION --output none
        echo -e "${GREEN}✅ Resource group '$RESOURCE_GROUP_NAME' created.${NC}"
    fi
    echo ""
}

# Function to create Azure AI service
create_ai_service() {
    echo -e "${BLUE}🤖 Creating Azure AI Service...${NC}"
    
    if az cognitiveservices account show --name $AI_SERVICE_NAME --resource-group $RESOURCE_GROUP_NAME --output none 2>/dev/null; then
        echo -e "${YELLOW}⚠️  AI service '$AI_SERVICE_NAME' already exists.${NC}"
    else
        az cognitiveservices account create \
            --name $AI_SERVICE_NAME \
            --resource-group $RESOURCE_GROUP_NAME \
            --location $LOCATION \
            --kind OpenAI \
            --sku S0 \
            --output none
        echo -e "${GREEN}✅ AI service '$AI_SERVICE_NAME' created.${NC}"
    fi
    echo ""
}

# Function to deploy model
deploy_model() {
    echo -e "${BLUE}🚀 Deploying GPT-4 Model...${NC}"
    
    # Check if deployment already exists
    if az cognitiveservices account deployment show \
        --name $AI_SERVICE_NAME \
        --resource-group $RESOURCE_GROUP_NAME \
        --deployment-name $DEPLOYMENT_NAME \
        --output none 2>/dev/null; then
        echo -e "${YELLOW}⚠️  Model deployment '$DEPLOYMENT_NAME' already exists.${NC}"
    else
        az cognitiveservices account deployment create \
            --name $AI_SERVICE_NAME \
            --resource-group $RESOURCE_GROUP_NAME \
            --deployment-name $DEPLOYMENT_NAME \
            --model-name gpt-4 \
            --model-version "0613" \
            --model-format OpenAI \
            --scale-settings-scale-type "Standard" \
            --scale-settings-capacity 10 \
            --output none
        echo -e "${GREEN}✅ Model deployment '$DEPLOYMENT_NAME' created.${NC}"
    fi
    echo ""
}

# Function to get configuration values
get_azure_config() {
    echo -e "${BLUE}📋 Retrieving Configuration...${NC}"
    
    # Get endpoint and key
    AZURE_AI_ENDPOINT=$(az cognitiveservices account show \
        --name $AI_SERVICE_NAME \
        --resource-group $RESOURCE_GROUP_NAME \
        --query properties.endpoint -o tsv)
    
    AZURE_AI_KEY=$(az cognitiveservices account keys list \
        --name $AI_SERVICE_NAME \
        --resource-group $RESOURCE_GROUP_NAME \
        --query key1 -o tsv)
    
    echo -e "${GREEN}✅ Configuration retrieved successfully!${NC}"
    echo ""
}

# Function to create environment file
create_env_file() {
    echo -e "${BLUE}📄 Creating Environment Configuration...${NC}"
    
    ENV_FILE="/workspaces/agentic-ai-app-for-java-sample/.env"
    
    cat > $ENV_FILE << EOF
# Azure Configuration (Generated by setup-azure.sh)
# Generated on: $(date)

# Azure Subscription Information
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_TENANT_ID=$TENANT_ID

# Azure AI Service Configuration
AZURE_AI_ENDPOINT=$AZURE_AI_ENDPOINT
AZURE_AI_KEY=$AZURE_AI_KEY
AZURE_AI_DEPLOYMENT=$DEPLOYMENT_NAME

# Application Configuration
AI_PROVIDER=azure
AZURE_AI_TEMPERATURE=0.7
AZURE_AI_MAX_TOKENS=2048

# Azure CLI Authentication (for MCP Server)
# These will be automatically populated if you're logged in via az cli
AZURE_CLIENT_ID=\$(az account show --query user.name -o tsv 2>/dev/null || echo "")
AZURE_CLIENT_SECRET=""
AZURE_TENANT_ID=$TENANT_ID
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
EOF

    echo -e "${GREEN}✅ Environment file created: $ENV_FILE${NC}"
    echo ""
}

# Function to update application properties
update_app_properties() {
    echo -e "${BLUE}⚙️  Updating Application Properties...${NC}"
    
    # Create/update development properties to use Azure
    DEV_PROPS="/workspaces/agentic-ai-app-for-java-sample/src/main/resources/application-azure.properties"
    
    cat > $DEV_PROPS << EOF
# Azure-specific configuration (Generated by setup-azure.sh)
server.port=8080
server.servlet.context-path=/api

# Database Configuration (H2 for development)
spring.datasource.url=jdbc:h2:mem:vibecode_dev
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Azure AI Configuration
vibecode.ai.provider=azure
vibecode.ai.azure.endpoint=$AZURE_AI_ENDPOINT
vibecode.ai.azure.key=$AZURE_AI_KEY
vibecode.ai.azure.deployment-name=$DEPLOYMENT_NAME
vibecode.ai.azure.temperature=0.7
vibecode.ai.azure.max-tokens=2048

# Security Configuration
vibecode.security.jwt.secret=vibecode-studio-azure-dev-secret
vibecode.security.jwt.expiration=86400000

# Cost Management
vibecode.cost.default-monthly-limit=100.0
vibecode.cost.alert-threshold=0.8

# GuardRail Configuration
vibecode.guardrail.enabled=true
vibecode.guardrail.strict-mode=false
vibecode.guardrail.allowed-packages=org.springframework,com.fasterxml.jackson,org.hibernate

# Logging
logging.level.com.vibecode=DEBUG
logging.level.com.azure=INFO
EOF

    echo -e "${GREEN}✅ Application properties updated: $DEV_PROPS${NC}"
    echo ""
}

# Function to show next steps
show_next_steps() {
    echo -e "${GREEN}🎉 Azure Setup Complete!${NC}"
    echo ""
    echo -e "${BLUE}📋 Next Steps:${NC}"
    echo "1. Start the application with Azure profile:"
    echo "   mvn spring-boot:run -Dspring-boot.run.profiles=azure"
    echo ""
    echo "2. Or load environment variables:"
    echo "   source .env"
    echo "   mvn spring-boot:run"
    echo ""
    echo "3. Test the configuration:"
    echo "   curl -X POST http://localhost:8080/api/projects/create \\"
    echo "     -H \"Content-Type: application/json\" \\"
    echo "     -d '{\"prompt\": \"Create a hello world Spring Boot app\", \"userId\": \"test-user\"}'"
    echo ""
    echo -e "${BLUE}🔧 Configuration Summary:${NC}"
    echo "   Azure AI Endpoint: $AZURE_AI_ENDPOINT"
    echo "   Deployment Name: $DEPLOYMENT_NAME"
    echo "   Resource Group: $RESOURCE_GROUP_NAME"
    echo "   Subscription: $SUBSCRIPTION_NAME"
    echo ""
    echo -e "${YELLOW}💡 Tip: Your credentials are stored in .env file and application-azure.properties${NC}"
}

# Main execution flow
main() {
    echo -e "${BLUE}Starting Azure CLI setup for VibeCode Studio...${NC}"
    echo ""
    
    # Check prerequisites
    check_azure_login
    get_subscription_info
    
    # Create Azure resources
    create_resource_group
    create_ai_service
    deploy_model
    
    # Configure application
    get_azure_config
    create_env_file
    update_app_properties
    
    # Show completion
    show_next_steps
}

# Handle script arguments
case "${1:-setup}" in
    "setup")
        main
        ;;
    "config-only")
        echo -e "${BLUE}Retrieving existing configuration...${NC}"
        check_azure_login
        get_subscription_info
        get_azure_config
        create_env_file
        update_app_properties
        show_next_steps
        ;;
    "clean")
        echo -e "${YELLOW}🧹 Cleaning up Azure resources...${NC}"
        echo "This will delete the resource group: $RESOURCE_GROUP_NAME"
        read -p "Are you sure? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            az group delete --name $RESOURCE_GROUP_NAME --yes --no-wait
            echo -e "${GREEN}✅ Cleanup initiated.${NC}"
        else
            echo -e "${YELLOW}Cleanup cancelled.${NC}"
        fi
        ;;
    "help"|"-h"|"--help")
        echo "VibeCode Studio Azure CLI Setup"
        echo ""
        echo "Usage: $0 [command]"
        echo ""
        echo "Commands:"
        echo "  setup       Create Azure resources and configure application (default)"
        echo "  config-only Retrieve configuration from existing resources"
        echo "  clean       Delete all created Azure resources"
        echo "  help        Show this help message"
        echo ""
        ;;
    *)
        echo -e "${RED}❌ Unknown command: $1${NC}"
        echo "Run '$0 help' for usage information."
        exit 1
        ;;
esac